config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :tasks, except: [:index]

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@tasks = Task.all
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
    render :show_form
  end

  def create
    @task = Task.create(task_params)
    @tasks = Task.all
    render :hide_form
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    @tasks = Task.all
  end

  def edit
    @task = Task.find(params[:id])
    render :show_form
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(task_params)
    @tasks = Task.all
    render :hide_form
  end


  private
  def task_params
    params.require(:task).permit(:title, :note, :completed)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Todo
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .jumbotron
        %h1
          Todo
          %small Tutorial Application
        = link_to 'New task', new_task_path,  class:  'btn btn-primary', remote: true
    = yield

app/views/pages/home.html.haml
#task-list.container
  = render partial: 'tasks/task_list', locals: {tasks: @tasks}
#modal.modal.fade

app/views/tasks/_task_form.html.haml
.modal-header
  %h1 
    = task.new_record? ? 'New Task' : "Editing task #{task.title}"
= simple_form_for task, class: 'clearfix', remote: true do |f|
  .modal-body
    = f.input :title
    = f.input :note
    = f.input :completed, as: :string, input_html: {class: 'datepicker'}
  .modal-footer
    = f.submit 'Save', class: 'btn btn-primary'

:javascript
  $(function() {
    $( ".datepicker" ).datepicker({format: 'yyyy-mm-dd'});
  });

app/views/tasks/_task_list.html.haml
- if tasks.empty?
  %span.text-warning There are no tasks!
- else
  %table.table.table-hover.table-bordered
    %thead
      %tr
        %th Title
        %th Created at
        %th Completed
    %tbody
      - tasks.each do |task|
        %tr
          %td
            %strong= task.title
          %td.text-info= task.created_at
          %td.text-success= task.completed
          %td
            = link_to task_path(task), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete task #{task.title}"} do
              %i.icon-remove
            = link_to edit_task_path(task), remote: true do
              %i.icon-edit